# generated by datamodel-codegen:
#   filename:  jsonschema.json
#   timestamp: 2024-11-27T11:04:41+00:00

from __future__ import annotations

from enum import Enum
from typing import Union
from uuid import UUID

from pydantic import BaseModel, Field


class Credits(Enum):
    integer_10 = 10
    integer_20 = 20


class Module(BaseModel):
    id: Union[int, UUID] = Field(..., title='Id')
    name: str = Field(..., title='Name')
    professor: str = Field(..., title='Professor')
    credits: Credits = Field(..., title='Credits')
    registration_code: str = Field(..., title='Registration Code')
